### ISSUE TITLE
Some signatures turn the return type as a parameter

### ISSUE THREAD

**Issue by raizam** [mono/CppSharp#1008]
Hello,

You may help me on these weird cases, I have couple C signatures such as:
```c
struct nk_rect nk_widget_bounds(struct nk_context*);
```

which gets converted to:
```csharp
 [SuppressUnmanagedCodeSecurity]
[DllImport("Nuklear", CallingConvention =global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint="nk_widget_bounds")]
internal static extern void widget_bounds(Nuklear.nk_rect @return, Nuklear.nk_context* _0);
```

The return type `struct nk_rect` was translated to the parameter `Nuklear.nk_rect @return`.

What is causing this? How can I keep the original signature ?

Thanks in advance

**Comment by ddobrev** [comment]
@raizam in short, it's specifics of the ABI. It's this this kind of problems that make your option of generating just the P/Invokes a bad idea. We have put much work into our generator so that it handles all of these details for users as they are often difficult to handle by hand as you do. This is also why I preferred then and I prefer now for you to use your effort to fix any bugs we might have instead of doing everything manually.
Still, if you insist on working this way, just generate a regular binding, go to the wrapper of this particular function and copy its body where we handle such parameters.

**Comment by raizam** [comment]
I've fixed it by removing the CheckAbiParameters pass.

@ddobrev I might help in the future, now that I'm getting a better understanding of cppsharp, but for now I'm happy with the results I'm getting with my version.

**Comment by tritao** [comment]
Hey @raizam,

Can you send a PR that disables the `CheckAbiParameters` in case we are parsing C code?

**Comment by raizam** [comment]
Hey @tritao, currently I can't send PRs as I made all my changes in the master branch and I would need to recreate a clean fork with a proper branch dedicated for my changes.

About that CheckAbiParameters, I feel like disabling the VisitFunctionDecl in C context wouldn't be enough, this bug might be present in C++ context as well.
I'm not sure what Function.IsReturnIndirect means, but in my case it seemed to get enabled when a type is returned by value and the use of the struct keyword might have caused it.

Maybe the best approach would be to check the calling convention used. 
In which calling conventions these indirect parameters occurs?
