### ISSUE TITLE
Delegates namespace is not declared

### ISSUE THREAD

**Issue by rokups** [mono/CppSharp#1021]
Wrapper build produces following error:
```
error CS0234: The type or namespace name `Delegates' does not exist in the namespace `Urho3D'. Are you missing an assembly reference?
```

`Delegates` appears in generated wrapper only twice:
```cs
public virtual void Dispose(bool disposing)
{
    if (__Instance == IntPtr.Zero)
        return;
    global::Urho3D.Urho3D.RefCounted __dummy;
    NativeToManagedMap.TryRemove(__Instance, out __dummy);
    ((global::Urho3D.Urho3D.RefCounted.__Internal*) __Instance)->vptr_RefCounted = new global::System.IntPtr(__OriginalVTables[0]);
    if (disposing)
    {
        var __slot = *(void**) ((IntPtr) __OriginalVTables[0] + 0 * 8);
        var ___dtorDelegate = (global::Urho3D.Delegates.Action_IntPtr) Marshal.GetDelegateForFunctionPointer(new IntPtr(__slot), typeof(global::Urho3D.Delegates.Action_IntPtr));
        ___dtorDelegate((__Instance + __PointerAdjustment));
    }
    if (__ownsNativeInstance)
        Marshal.FreeHGlobal(__Instance);
    __Instance = IntPtr.Zero;
}
```
```cs
// virtual ~RefCounted()
private static global::Urho3D.Delegates.Action_IntPtr _dtorDelegateInstance;
```
Namespace declaration is not generated.

OS: Archlinux
Target: GCC
Code: [Program.cs.txt](https://github.com/mono/CppSharp/files/1535380/Program.cs.txt)
Headers: https://github.com/urho3d/Urho3D/tree/master/Source/Urho3D/Container
In order to reproduce you would need SDK from https://sourceforge.net/projects/urho3d/files/Urho3D/Snapshots/
You may need to remove `#define URHO3D_SSE` from `include/Urho3D/Urho3DAll.h` header.

**Comment by tritao** [comment]
Those delegates are processed here: https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/DelegatesPass.cs#L23

Might be a good starting point to figure this one out.

**Comment by rokups** [comment]
I will, thanks for hints

**Comment by rokups** [comment]
From what i gathered it seems there should be a global (static?) class named `Delegates` which should declare delegate `Action_IntPtr`. Still cant figure out where that is supposed to happen.

**Comment by ddobrev** [comment]
@rokups the name-space is created at https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/DelegatesPass.cs#L195 and attached to the AST at https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/DelegatesPass.cs#L32 . There's something wrong we do in your case and you'd need to figure out what.

**Comment by rokups** [comment]
And how does this namespace is supposed to get printed? Still bit struggling to understand how exactly CppSharp ticks :)

**Comment by ddobrev** [comment]
This name-space is, or rather, should be :), added to our AST and then generated as any other name-space.

**Comment by rokups** [comment]
And is it supposed to be generated [here](https://github.com/mono/CppSharp/blob/master/src/Generator/Generators/CSharp/CSharpSources.cs#L158)? Because that method does not visit `Delegates` namespace and i cant tell where else it could be created.

**Comment by frankenherm** [comment]
@rokups do you remember how you solved this, I have the exact same issue currently?

**Comment by rokups** [comment]
I really do not, this was so long ago... Sorry for not posting a solution, this is like the most ass thing one could do.. 😅 However, i can tell you this much - my usecase was so complicated that it brought out so many issues and rough edges of CppSharp that i... just... switched to... SWIG 💥

**Comment by frankenherm** [comment]
oh no, anyway, thank you for your quick reply. I will try to post a solution if I solve this ..again :)

**Comment by frankenherm** [comment]
@tritao I could not strip my project enough to make it publicly uploadable. But I debugged this evening and it seems to be generated correctly from the `DelegatesPass`. The namespace is also added to a `TranslationUnit`. 
The delegates are then removed from the AST Context in the next Pass here: https://github.com/mono/CppSharp/blob/169f8686a932d2269be97fdf123d66761039f15e/src/Generator/Passes/StripUnusedSystemTypesPass.cs#L89C31-L89C31

I do not have a solution yet, the delegates seem to be marked as unused. Perhaps you've got an idea, otherwise I will debug tomorrow again.

**Comment by frankenherm** [comment]
That's what I did now:
- set the delegates' `GenerationKind` explicitly to `Generate`
- added `StripUnusedSystemTypesPass` to their `ExcludeFromPasses` list.

doubled it just to be sure :) for me this workaround is sufficient, though I would not recommend this as PR-able solution ;)

I am not able to find out where it should be visited in the AST to be marked as used. The delegates are mainly from destructors, if this helps.

**Comment by frankenherm** [comment]
They were generated as destructors of my wrapping classes. 
I tried to write an example for you, but the two delegates in question disappeared from the `std` namespace when I excluded the referenced `std::exception` class from generating (because it had an error, too). Perhaps they were in the wrong namespace in the first place and should be in my own namespace anyway. 

I'd upload my wrapper as private repo and invite you to investigate further, if you like to.

**Comment by tangosd** [comment]
Hello I am having the same issue, Delegate is not generated (they are called from several destructors). @frankenherm have you resolved it?

**Comment by frankenherm** [comment]
Hi, this was exactly my problem, it was only used in destructors and therefore not seen as used. I disabled the removal of unused std-classes, which was sufficient for me. 

The issue resolved itself afterwards, since I excluded the Error class from generating due to an unrelated error. I suppose it was a combination of both issues?

**disable removal of std-classes:**
I do not know how to disable default-passes, but I adapted the code [here](https://github.com/mono/CppSharp/blob/03874e743fc663879a124f3d37dd7b81d4ceedc7/src/Generator/Passes/StripUnusedSystemTypesPass.cs#L87C6-L87C6) to skip removal. Seemed a bit brute forced, but I was unable to spend much more time with this issue.

**exclude Error from generating:**
override Preprocess of `ILibrary` with:
```
public void Preprocess(Driver driver, ASTContext ctx)
{
    var errorClass = ctx.FindClass("Error");
    foreach (var error in errorClass)
    {
        error.GenerationKind = GenerationKind.None;
    }
}
``` 

Hope this helps in any form.

**Comment by tangosd** [comment]
@frankenherm thank you, disabling the removal of std-classes did the trick.
It is probably unrelated (a bit similar though) but now I have Std.FuncClass not declared in Std.Function . 
Don't mind this problem if you don't know what could be the reason.
