### ISSUE TITLE
End-to-end example

### ISSUE THREAD

**Issue by mathiasi** [mono/CppSharp#1073]
Disclaimer: I'm novice when it comes to C# and C++ interaction which is why I found this project appealing. I've been following the "Generating bindings" and managed to produce  four files: Sample.cs, Std.cs, Sample-symbols.cpp and Std-symbols.cpp but how do I proceed from here? As a novice user I've would really appreciate having a more in-depth tutorial that covers e.g. Visual Studio which I'm guessing most people will be using. I've been trying to mess around with adding different types of C++ projects in VS but never got it to work.
Thanks.

**Comment by tritao** [comment]
You will need to compile the outputs generated by CppSharp.

For the managed code, optionally you can set the `CompileCode` option to true, which will generate a managed `Sample.dll` for you.

The native code needs to be compiled by a Visual C++ project. You should choose the DLL output option and also remember to annotate the symbols with a `__declspec(dllexport)` attribute so that they get exported in the DLL by the native linker.

We currently have no documentation for the compilation of the generated native outputs, but you can use any guide online related to C++ DLL compilation with Visual Studio.
