### ISSUE TITLE
Split generated code by types enums, structs, classes, interfaces

### ISSUE THREAD

**Issue by QuantumDeveloper** [mono/CppSharp#1095]
Does this feature is available now. It would be quite convenient to have automatic splitting those type on separate files, especially if generated file is too large.
I know that for now Generator could split on separate file by headers, but what about splitting by headers and/or types?

**Comment by ddobrev** [comment]
It's not available, and I need to tell you neither @tritao nor I is going to do it. Our time has been extremely limited lately and we won't spend it on a feature which I understand you find useful but is essentially cosmetic. I'd also not take somebody else's code because it would require way too many changes and I don't want any complication in our code unless absolutely necessary.

**Comment by tritao** [comment]
I think this could be done with a pass, if it's self-contained I would not mind merging it in, but as @ddobrev said, we will not be working on this feature.

**Comment by QuantumDeveloper** [comment]
OK, thanks for your answer. 
Could you please also write some comments regarding #1088 ?

**Comment by lostmsu** [comment]
@QuantumDeveloper did you figure this one out? Also, how do I split by header? I essentially only add a single "uber" header, that includes all others, and all the code ends up in the same file.

**Comment by QuantumDeveloper** [comment]
@lostmsu Hah. I ended up with creating my own binding generator based on clang to accomplish this task :)
