### ISSUE TITLE
C++ string parameter instance duplicates

### ISSUE THREAD

**Issue by mattparks** [mono/CppSharp#1096]
##### Brief Description
The C# generated output from a virtual method that takes two strings (or three) as parameters generates duplicate names for string instances. 

C++ input: https://pastebin.com/HrBkVT87
Generated C# output: https://pastebin.com/4CyMcfag

Errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0128	A local variable or function named '__basicStringRet' is already defined in this scope	TestSharp	C:\Users\mattp\Documents\Flounder Workspace\TestSharp\TestSharp\Test.cs	110	Active
```

OS: Windows
Target: MSVC

Driver: https://pastebin.com/vAWeTgua

**Comment by tritao** [comment]
Thanks for the bug report.

The issue is in this code:

https://github.com/mono/CppSharp/blob/695a7538d11db4fe7fef6c1f1d77dd0284267ce7/src/Generator/Types/Std/Stdlib.cs#L101

https://github.com/mono/CppSharp/blob/695a7538d11db4fe7fef6c1f1d77dd0284267ce7/src/Generator/Types/Std/Stdlib.cs#L112

I think this just needs to be changed to something like this:

```
const string varBasicString = $"__basicStringRet{ctx.ParameterIndex}";
```

Do you want to try sending a PR fixing this issue?
