### ISSUE TITLE
Invalid code is generated when a nameless C union contains a struct with an _0 field

### ISSUE THREAD

**Issue by Wodann** [mono/CppSharp#1225]
##### Brief Description
Using a nameless C union that itself contains a struct with an `_0` field, results in the creation of an  `public unsafe partial struct _0` struct for internal data representation, as well an `_0` property for obtaining the underlaying struct's field: `public global::Se4Core.SE4IpAddr._0 _0`.

This results in a CS0102 error: The type `Se4Core.SE4IpAddr` already contains a definition for `_0`.

I expect the same error to occur when `_1`, `_2`, etc. fields are used.
This could probably be solved by prepending the `_0` type with the class' name. E.g. `SE4IpAddr_0`.

OS: Windows (NuGet package: 0.9.2 x64)

##### Used headers
```C
typedef enum SE4IpAddr_Tag {
    V4,
    V6,
} SE4IpAddr_Tag;

typedef struct {
    uint8_t _0[4];
} SE4V4_Body;

typedef struct {
    uint8_t _0[16];
} SE4V6_Body;

typedef struct {
    SE4IpAddr_Tag tag;
    union {
        SE4V4_Body v4;
        SE4V6_Body v6;
    };
} SE4IpAddr;
```

##### Used settings

Target: MSVC

##### Stack trace or incompilable generated code
The C# error occurs in line 416 of the following SE4Core.cs file:
[Se4Core.txt](https://github.com/mono/CppSharp/files/3255781/Se4Core.txt)

**Comment by ddobrev** [comment]
@Wodann thank you for your report. I've never expected something as ugly as _0 to be used as a real identifier. We're going to discuss our options and we'll definitely have your suggestion in mind – we'd just really like to come up with something shorter. We'll let you know about any developments.

**Comment by NickApps** [comment]
Hi, I have also run in to this recently.  The problem is also slightly worse than it first seems as multiple anonymous unions within a type will result in omission of latter ones from the list of properties.  

I've made some changes that can now cope with the simplest of test classes:
`struct SimpleAnonUnion
{
	union
	{
		void* a1;
		void* b1;
	};

	union
	{
		void* a2;
		void* b2;
	};
};`

During the preprocess stage of my ILibrary implementation I can manipulate the Name and OriginalName values of the classes created for the anonymous types such that the generated code can compile, but only when a single anonymous union is defined.

To cope with multiple classes, I've had to change the way USR values are generated for the fields and classes representing anonymous types.  I agree the _0, _X names aren't nice, but I've not changed this (yet).  @ddobrev Happy to share/contribute my changes with some guidance.

**Comment by ddobrev** [comment]
@Wodann @NickApps I hit this problem myself today. We decided to simply ignore anonymous types and generate the contained fields instead. This way the API is only improved and we don't need to think about complicated ways to generate ugly names.

**Comment by tritao** [comment]
Can this be closed now?
