### ISSUE TITLE
Static methods can create name-space conflicts when wrapped with C++/CLI

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#365]
To reproduce, go to CLITemp.h and move testStdString from its class to a free function.

**Comment by genuinelucifer** [comment]
I reproduced the issue and fixed it by generating a 'FileName + "Class" ' for all the free functions instead of the 'FileName' used earlier. I made the changes only for CLI generator.
But, I guess it would be better to be uniform across CSharp and CLI generators regarding naming conventions. So, please give review my work and if it is acceptable i will add the changes to CSharp generator as well.
My work:
https://github.com/genuinelucifer/CppSharp/commit/8b01d4a9702c5702af309c3824f86de6fb8a1095

**Comment by genuinelucifer** [comment]
@ddobrev also please see if FIleName + "Class" solution is acceptable only as a change in C++/CLI generator! SInce, the C# generator works fine without any changes so is it fine to leave it be?

**Comment by ddobrev** [comment]
I am afraid @tritao has the final say here as well. I am not really familiar with the C++/CLI end. What I do know, I've already mentioned.

**Comment by tritao** [comment]
We try to keep the behavior uniform between the C# and C++/CLI backends so it would be better to fix this so it works the same between backends. 

Just going from the description I cannot easily see what the problem is though. What is the actual problem here @ddobrev?

**Comment by ddobrev** [comment]
@tritao I don't remember, I would need to see some generated code. I hit that by accident when writing a test for something completely unrelated and filed this so that it's not forgotten. What I meant was that the "Class" appendage is not appropriate because the functions in question are classless.

**Comment by genuinelucifer** [comment]
@tritao The problem is that for free functions (not contained in any class)
in the header a new class is created with same name as the file and since
there is a top level namespace created with the same name as the file so
these both names result in conflict.
Ex:
If ClassA and ClassB are in Basic.h and a free function "Func" is also
there then we generate a namespace Basic which contains the two classes AND
a class named Basic which has the "Func".
Now, we reference ClassB from ClassA with Basic::ClassB which results in
the error that ClassB is not a member of Basic. Because now the class Basic
is in scope NOT the namespace.
So, either we rename the namespace or the clas that is generated for free
function. (this seems to be one obvious solution)

**Comment by tritao** [comment]
https://github.com/mono/CppSharp/commit/cf472f526c87e9807a9f9868e7cbc07376efcbb6 should have fixed this.
