### ISSUE TITLE
Fixed size array in struct

### ISSUE THREAD

**Issue by GeorgeR** [mono/CppSharp#380]
CppSharp is giving an erroneous result for when you have a fixed size array in a type. So for example, put this in CSharpTemp/CSharpTemp.Native/CSharpTemp.h inside the Bar class:

Foo foos[4];

Generating that will show the errors (C# can't do it for non primitive-ish types), and I don't know the best alternative implementation.

**Comment by tritao** [comment]
@genuicelucifer Would you be interested in trying to tackle this one?

**Comment by genuinelucifer** [comment]
@tritao Will try. As per the look of it, most of the work is already done. Or am i missing something?!

**Comment by tritao** [comment]
Possibly, I haven't touched this in a bit so I'm not exactly sure what we need besides my previous comments on this thread.

**Comment by genuinelucifer** [comment]
@tritao While trying to generate it I found that no property was generated for ```foos``` if it is kept private. Property is only generated if it is a public member. Is there a specific reason not to generate private properties?

**Comment by tritao** [comment]
I think the reason we do not generate those is to keep the API as close as possible to C#. If we generated the property as private then the user would not be able to call it anyway. And if we generated private C++ properties as public in C# then we're changing the API of the original code. Though... I think we do support something like this for protected methods because of the multiple inheritance support, you can call protected members inherited from a base. @ddobrev knows more about that than me.

**Comment by genuinelucifer** [comment]
Oh I see. :+1:

**Comment by genuinelucifer** [comment]
@tritao I have fixed the getter. But, i am unable to think of a way to convert the Foo or Foo.Internal* object to byte* to store back in the setter.

**Comment by ddobrev** [comment]
@genuinelucifer since a pointer to anything is just a pointer, wouldn't a simple cast from Foo.Internal* to byte* work?

**Comment by genuinelucifer** [comment]
@ddobrev Done. Thanks :)
