### ISSUE TITLE
Documentaion on "Compiling LLVM on Windows/Visual Studio"

### ISSUE THREAD

**Issue by Dreamwalker666** [mono/CppSharp#412]
In the documentation it says to make a build directory then change into it then run CMAKE.  This will fail as CMAKE won't find the cmake file it needs.

How should this section be performed?

**Comment by tritao** [comment]
Try `cd build` and then `cmake ..`.

**Comment by tritao** [comment]
What are you trying to invoke and what error do you get?

**Comment by Dreamwalker666** [comment]
Well the process says:

-  Clone CppSharp to <CppSharp>
-  Clone LLVM to <CppSharp>\deps\llvm
-  Clone Clang to <CppSharp>\deps\llvm\tools\clang
-  Create directory <CppSharp>\deps\llvm\build

then

-  cd <CppSharp>\deps\llvm\build
- cmake -G "Visual Studio 12" .....
- msbuild LLVM.sln /p:Configuration=RelWithDebInfo;Platform=Win32 /m

But you have just created the directory so there will be no cmakelists.txt for cmake to use?

**Comment by tritao** [comment]
So you haven't actually tried it?

We pass the parent directory to CMake (which has the needed files) with the `..` argument what the end. Perhaps if you actually paste some _actual error message_ as in copy/paste what you're trying and the output I can actually give some directed help instead of trying to guess what problem you're facing.

**Comment by Dreamwalker666** [comment]
Yes I tried it and my mistake was I missed the ".." at the end of the line sorry.
