### ISSUE TITLE
Arrays of constant-size are ignored

### ISSUE THREAD

**Issue by CPPAndCSharpStudent** [mono/CppSharp#416]
In an attempt to learn more about CppSharp tool itself, I tried to test it against gmp.h and gmpxx.h and both have failed despise my attempt in manipulating the settings and I was unable to understand why this failed.

I get a lot of errors like this:

Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Typedef 'mpz_t' was ignored due to unsupported type
    Typedef 'mpq_t' was ignored due to unsupported type
    Typedef 'mpf_t' was ignored due to unsupported type

Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Function '__gmpz_init' was ignored due to ignored param
    Function '__gmpz_init2' was ignored due to ignored param
    Function '__gmpz_inits' was ignored due to ignored param

Please and thank you.

**Comment by tritao** [comment]
From GMP's headers I see the following:

```typedef __mpz_struct mpz_t[1];```

So those types are really arrays of constant-size 1. I'll need to follow up later on this one to see if we can support this better.

**Comment by CPPAndCSharpStudent** [comment]
It also seems to happen for a lot of different libraries, but I am  not sure why is this kind of error preventing the extern methods functions from using pointers instead of structs? It would make more sense to use the pointer whenever type object cannot be parsed.

**Comment by tritao** [comment]
There's no technical reason we can't generate the externs for those types, it's just no one requested that before. I can see it would be useful to export them since then some higher-level API could be written by hand for them.

**Comment by tritao** [comment]
I did some checking to see why this does not work yet...

We ignore non-primitive constant arrays here: https://github.com/mono/CppSharp/blob/master/src%2FGenerator%2FPasses%2FCheckIgnoredDecls.cs#L345

The main reason we don't currently support it is because C# has a limitation on fixed size buffers (only primitive types are supported): https://msdn.microsoft.com/en-us/library/vstudio/zycewsya%28v=vs.100%29.aspx

Now, that is only a problem when marshalling structs that have these types as part of their internal members. For just parameter passing, as you said, we can decay to pointers in the externs, and use regular C# arrays and just check that they have the right size at runtime.

If you'd like to try implementing this, you can take some guidance from this commit: https://github.com/mono/CppSharp/commit/4c5d933cd2e74fe3da94d0f3c81f934e2ba25ff6

And me and @ddobrev will be here for any assistance.

**Comment by tritao** [comment]
Related issue: https://github.com/mono/CppSharp/issues/380

**Comment by CPPAndCSharpStudent** [comment]
Thank you, I'll try to research into Clang AST to see (it'd be helpful for any materials you can list that I should read about) and I'll try to find a way to implement this.

**Comment by genuinelucifer** [comment]
@CPPAndCSharpStudent @tritao shouldn't this issue have been solved with the recent commits?

**Comment by tritao** [comment]
I think so.
