### ISSUE TITLE
Supporting PowerPC target?

### ISSUE THREAD

**Issue by KonajuGames** [mono/CppSharp#458]
How difficult would it be to add support for a PowerPC target?
- Add support for any special ABI requirements.
- Rebuild LLVM to support PPC.
- Anything else?

**Comment by tritao** [comment]
I assume you mean generating bindings that work on a PowerPC target system and not running CppSharp on a PowerPC host.

I wouldn't expect much difficulty in adding support for a new target but it depends on the C++ ABI model of the target. Assuming this is for Xbox 360, I would expect it uses the same Microsoft C++ ABI that we already support.

LLVM support for PowerPC is not needed since we're not generating any code with the LLVM code generator backends. The only thing it might gives us is support for passing PowerPC triples to Clang, but I don't think it supports Xbox 360 triples so it wouldn't give us that much.

I think the best bet is starting with a regular desktop 32/64-bit triple and adjust ABI alignment values and go from there.
