### ISSUE TITLE
fail to generate cs file for function with union as argument

### ISSUE THREAD

**Issue by chunseoklee** [mono/CppSharp#615]
```cpp
#include <stdio.h>
typedef union {
  int c;
  int d[10];
} union_t;
struct test_struct2                                                            
  int b;
  union_t u;
};
int func_union(union_t u) {
}

int func(struct test_struct2 *p) {
}
```
The code above failed to generate cs file for ```func_union```.  
I think CppSharp omitted functions that get union structure as an argument.
Could someone help me to resolve this issue ? or this feature is not implemented yet ?

**Comment by tritao** [comment]
I took a quick look and this is because we ignore the typedef declaration, the relevant code is https://github.com/mono/CppSharp/blob/master/src%2FGenerator%2FPasses%2FCleanInvalidDeclNamesPass.cs#L118.

If I remove that whole method, your example code works. @ddobrev do you know if we can safely get rid of this code?
