### ISSUE TITLE
1 Byte aligned dlls

### ISSUE THREAD

**Issue by dowitdo** [mono/CppSharp#617]
How can I use a c++ dll that is compiled using 1 byte structure alignment? I couldn't find a setting for this. Is it even possible to use 1 byte aligned dlls?

**Comment by tritao** [comment]
Yes this is possible. If your structs in C/C++ have been declared in the headers with the proper `declspec(align)` attributes then it should work automatically. If you instead force all structs to be packed instead using a compiler flag, then you should pass the same compiler flag to CppSharp using `options.Arguments` (in MSVC case it's the `/Zp1` compiler flag).

**Comment by dowitdo** [comment]
Neither seem to work for me. In my header I used 

_declspec(align(1)) class Foo
{
public:
	_declspec(dllexport) Foo();

    int a;
...

I also added 

    class SampleLibrary : ILibrary
    {
        /// Setup the driver options here.
        public void Setup(Driver driver)
        {
            DriverOptions options = driver.Options;
            options.GeneratorKind = CppSharp.Generators.GeneratorKind.CSharp;
            options.LibraryName = "sample";
            options.addArguments("/Zp1");

Neither of the changes seem to make a difference. The created .cs files are identical to when the changes were not made. What am I missing?

I think it would be a useful feature, but since you have a workaround, it is fine as is.

**Comment by tritao** [comment]
OK I see where the problem is.

From MSDN: ```Use __declspec(align(#)) to precisely control the alignment of user-defined data (for example, static allocations or automatic data in a function).```

This option does not do what you think it does. It is used to control where usages of `Foo` in your case will be aligned, so if you declared a `Foo foo` variable either inside a class or as a local variable, then that particular usage would be aligned to the value you specify. 

The compiler will even warn you that it does not make sense: `1>g:\dev\cppsharp\tests\common\common.h(1052): warning C4359: 'Foo': Alignment specifier is less than actual alignment (4), and will be ignored.`

Try like this instead:

```
#pragma pack(push,1)
class DLL_API TestAlignDirectives
{
public:
	TestAlignDirectives();
	int a;
	int b;
};
#pragma pack(pop)
```

**Comment by dowitdo** [comment]
That worked.

Thanks tritao
