### ISSUE TITLE
Need a way to set SharedLibraryName option for each TranslateUnit

### ISSUE THREAD

**Issue by javagg** [mono/CppSharp#624]
currently, the SharedLibraryName cannot change during the generation in one Library which may include multiple translationUnits.

**Comment by tritao** [comment]
I'm not sure I understand the issue here...

There should just be one final shared library generated per library, so why do you need to change the name during generation?

**Comment by ddobrev** [comment]
@tritao there are two possible explanations:
1. @javagg, you want to have separate wrappers, perhaps one per header, for a single native library - we won't support this because it makes no sense;
2. @javagg, you want a wrapper per native library but do not know how to get it - you need to create one ILibrary implementation per native library and call ConsoleDriver.Run for each in succession. In case you use auto-compilation of the wrappers, you need to sort your libraries by dependencies so that each library only depends on ones before it in the list - you can use https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp.CLI/Program.cs#L82 for reference.

**Comment by ddobrev** [comment]
@javagg have you been able to handle this? If so, could you please close it?

**Comment by javagg** [comment]
@ddobrev I used your method, the problem is solved. Thanks!

**Comment by ddobrev** [comment]
@javagg excellent, I am glad you have fixed your problem. Just a small clarification: I meant to say you needed one ILibrary object per native library, not one implementation per library because you can pass headers and libraries to a single implementation thus avoiding code repetition.
