### ISSUE TITLE
Duplicate fields offsets in MI classes

### ISSUE THREAD

**Issue by tritao** [mono/CppSharp#659]
##### Brief Description

Noticed this issue in latest Qt# release.

##### Stack trace or incompilable generated code

QWidget has this native layout:

```csharp
	public class QWidget : QObject, IQPaintDevice, IDisposable
	{
		[StructLayout(LayoutKind.Explicit, Size = 24)]
		public new struct Internal
		{
			[FieldOffset(0)]
			public global::System.IntPtr vfptr0;

			[FieldOffset(4)]
			internal global::QtCore.QScopedPointer.Internal d_ptr;

			[FieldOffset(12)]
			public ushort painters;

			[FieldOffset(16)]
			public global::System.IntPtr reserved;

			[FieldOffset(20)]
			public global::System.IntPtr data;
		}
	}
```

QMenu, which inherits from QWidget, has this one:

```csharp
	public class QMenu : QWidget, IDisposable
	{
		[StructLayout(LayoutKind.Explicit, Size = 24)]
		public new struct Internal
		{
			[FieldOffset(0)]
			public IntPtr vfptr0;

			[FieldOffset(4)]
			internal QtCore.QScopedPointer.Internal d_ptr;

			[FieldOffset(4)]
			public ushort painters;

			[FieldOffset(8)]
			public IntPtr reserved;

			[FieldOffset(20)]
			public IntPtr data;
		}
	}
```

Notice the duplicated field offset, which is almost certainly wrong.

**Comment by ddobrev** [comment]
The original layout is wrong too. Compare to Clang's dump:

         0 | class QWidget
         0 |   class QObject (primary base)
         0 |     (QObject vtable pointer)
         4 |     class QScopedPointer<class QObjectData, struct QScopedPointerDeleter<class QObjectData> > d_ptr
         4 |       class QObjectData * d
         8 |   class QPaintDevice (base)
         8 |     (QPaintDevice vtable pointer)
        12 |     ushort painters
        16 |     class QPaintDevicePrivate * reserved
        20 |   class QWidgetData * data
           | [sizeof=24, dsize=24, align=4,
           |  nvsize=24, nvalign=4]

This is most probably a separate issue, though.
In addition, printing the layout is, at least in the case of QtSharp, easier in code than it is at the command line because of the many headers to include. All that has to be done is for the following to be pasted in "if (hasLayout) { ... }" in Parser::WalkRecord:

        if (RC->Name == "QMenu") // or any desired class
        {
            std::string s;
            llvm::raw_string_ostream as(s);
            C->getASTContext().DumpRecordLayout(Record, as);
            as.flush();
            printf("%s\n", s.data());
            __debugbreak();
        }

**Comment by ddobrev** [comment]
The best way to solve it is the simplest one: just copy the static DumpRecordLayout from https://github.com/llvm-mirror/clang/blob/master/lib/AST/RecordLayoutBuilder.cpp#L3152 and adjust it to collect the offsets instead of printing them. We need to then just store them in our AST, for example by adding a list of offsets or even entire internal fields to our AST::Class. This way we'll have the correct offsets from the very beginning and we'll be able to just delete the manual computation.

**Comment by ddobrev** [comment]
We should add a new field to AST::Class called OriginalFields or InternalFields. This list will contain all fields, including v-table pointers and fields from bases - in other words, everything DumpRecordLayout shows. This way we are guaranteed to always have the correct layout in the correct order with the correct offsets. The field of Fields we have now should be removed from the C++ AST and reimplemented in the managed AST to return those OriginalFields which belong to the current class and are not v-table pointers.

**Comment by ddobrev** [comment]
Fixed by https://github.com/mono/CppSharp/commit/e2b8f445659b8632523175b8bf245920a196a7ae.
