### ISSUE TITLE
Wrapping a C++/CX API?

### ISSUE THREAD

**Issue by tomspilman** [mono/CppSharp#676]
Are there any features in CppSharp to handle wrapping a [C++/CX](https://en.wikipedia.org/wiki/C%2B%2B/CX) API?

Currently i'm doing this likely the hard way using `#ifdef`s and custom C++ wrappers to hide away the C++/CX and generate an API that is consumable by CppSharp.

Is there a better way for me to do this?

**Comment by tritao** [comment]
We do not directly support this but it would be doable.

The majority of the work would be in teaching Clang to support the C++/CX syntax.

But we already did this before with our work on adding C++/CLI support to Clang (it lives in https://github.com/tritao/clang-cli/blob/cil/lib/Parse/ParseCLI.cpp).

So we'd need to rebase the work on that fork to a recent Clang revision, and switch C++# to use it instead of upstream. Then maybe slightly modify C++# to deal with any C++/CX specific AST nodes (mostly properties and attributes are what comes to mind).

What do you need it for?

**Comment by tomspilman** [comment]
> What do you need it for?

I'm wrapping some native console APIs to be available from C#.  It has been slow going how I am doing it now...  just looking to see if there are better options.

**Comment by tritao** [comment]
So just to recap you want to generate bindings for C++/CX APIs distributed by Microsoft (Xbox it sounds like). This definitely seems like something that CppSharp could help with and could be useful for some other Microsoft SDKs in the future.

CC'ing @migueldeicaza 

Do you think we should spend a few weeks to improve this use case?

**Comment by tritao** [comment]
Closing this as we do not have the resources to implement this for the foreseeable future.
