### ISSUE TITLE
Error when parsing headers referenced includes.

### ISSUE THREAD

**Issue by jpippy** [mono/CppSharp#83]
Just want to say, awesome project. Great concept, and it is unbelievable how easy you have made it for others.

I do have a question though. When CppSharp parses the headers I specify, I get an error about the headers that are referenced within the .h file, saying they can not be found. Mainly when they are in this format: "includes/types.h"

I am adding a folder for the includes as such:

options.IncludeDirs.Add(@"C:\Users\Joe\Documents\Testapp\lib\includes");

Then adding each header as such:

options.Headers.Add("interface.h");

Now I know I could bypass this, but I am wondering if their is a way to set ignore parameters on headers. So I could ignore certain strings? Unless there is another way of fixing this.

**Comment by sajivthomas** [comment]
I am running into the same issue while trying to create a C# wrapper for https://github.com/OpenKinect/libfreenect2 , and it has header files in different folders

**Comment by tritao** [comment]
Hi @sajivthomas, can you describe the issue you're experiencing in more detail?

**Comment by sajivthomas** [comment]
Hi @tritao whenever an include looks something like this for example:
#include <libfreenect2/packet_processor.h> 
It would throw parser error complaining that it cannot find packet_processor.h . The way I resolved it was to specify the full path to packet_processor.h and it worked. It works for my purposes as long as I can generate a C# wrapper.

Now, I am past all the parse errors, but there is another issue, but might need to tracked as a new issue?

Anyway I will briefly mention the issue. once its done with parsing all the header files and starts generating code it throws and error in the function 'GetVirtualCallDelegate' in this file \\CppSharp\src\Generator\Generators\CSharp\CSharpTextTemplate.cs

The reason is that Driver.Delegates[method] fails since there is no entry for the key in the dictionary. The method in this case is: virtual ~DepthPacketProcessor();

I can debug the code find out what's happening, but please let me know if there are obvious mistakes I might be making or if there is known issue.

**Comment by ddobrev** [comment]
@sajivthomas my apologies, I have been really busy lately and I haven't been able to check this bug. However, if you manage to fix it, I would gladly take a patch.

**Comment by sajivthomas** [comment]
No worries, I have been very busy too and was not able to spend any time lately. Attached is a patch that got the generator working. Not sure if it causes side effects or regressions ☺

Anyway it generated the C# files but now the files won’t compile after adding to a C# project. Any help would be very much appreciated.

Thanks,
Sajiv

**Comment by tritao** [comment]
Hey @sajivthomas, I cannot see any attachment from Github. Please link it here via a Github Gist or some other method so we can take a look.

About the errors, you will also have to post them so we can help. If you can get us a way to reproduce them even better, as that way it'll be more likely we can fix them.

**Comment by sajivthomas** [comment]
[st_branch.zip](https://github.com/mono/CppSharp/files/89573/st_branch.zip)

Attaching as zip. Let me try to get you the header files or maybe the entire solution for libfreenect2

**Comment by ddobrev** [comment]
@sajivthomas I am afraid we cannot tale this code. You have only fixed the symptom but not the problem itself - that destructor should not be missing from the delegates to begin with. However, you can definitely use this piece locally until we have the time to fix the real issue. Your suggestion of sending your solution would also help a great deal, we would be able to directly debug it and see what the problem is.

**Comment by sajivthomas** [comment]
I was not expecting the patch to be accepted anyway ☺. Didn’t spend a lot of time understanding the whole generator just wanted to see if I can at least get a quick and dirty solution. Anyway the source solution is uploaded here https://drive.google.com/file/d/0B6u4cYoRYGz6RlFKZmRWRkZmdmc/view?usp=sharing

/build/libfreenect2.sln is the solution and /build/freenect2.vcxproj is the project for which we want to create the C# wrapper.

Once you have made a fix could you please share you implementation of  CppSharp.ILbrary, I might be missing some settings and such.

-Sajiv

**Comment by ddobrev** [comment]
@sajivthomas thank you for sharing your code but I am afraid I cannot download it, do you perhaps need to adjust the permissions?

**Comment by sajivthomas** [comment]
Could you try now please.

**Comment by ddobrev** [comment]
It works now, thank you. We'll get back to you as soon as we've been able to debug it.

**Comment by ddobrev** [comment]
I can see now the package only contains the wrapped library, not the wrapping project itself. Is the latter closed source?

**Comment by sajivthomas** [comment]
The wrapping project (.NET library) would basically just contain out put from CppSharp generator. The idea is to then reference it in  a .NET application to interop with the native C++ library.

Anyway I uploaded wrapper project here - https://drive.google.com/file/d/0B6u4cYoRYGz6T0ViOThrTmx5WHc/view?usp=sharing for your reference as well. However, it does not compile. So, you would need to remove it from the solution to try the run the FreenectWrapperGenerator project.

FreenectWrapper project references the generated C# files.

**Comment by ddobrev** [comment]
@sajivthomas thank you. @tritao is going to be a little busy so I'll be responsible for checking the bug out. I'll let you know as soon as I have news.

**Comment by tritao** [comment]
By the way, it would be a good idea to create a new Github issue to track the problem. This issue has already been closed.

**Comment by sajivthomas** [comment]
@tritao Done. https://github.com/mono/CppSharp/issues/610
