### ISSUE TITLE
Invalid code generated for unnamed struct fields

### ISSUE THREAD

**Issue by ChrisJMarshall** [mono/CppSharp#872]
OS: Windows
Target: MSVC
Generator: CLI

##### Brief Description
I have a struct for a bit-packed data structure that uses unnamed fields for alignment purposes. CppSharp attempt to generate wrappers for the unnamed field and ends up with uncompilable code as a result. It should just ignore the fields.

##### Workarounds
The fields can be declared as private in the struct which stops CppSharp from trying to process them. Alternatively adding ctx.IgnoreClassField(<struct name>, "") to Preprocess suppresses the issue for the specified class.

**Comment by tritao** [comment]
This one should be easy to fix, want to try sending a PR with a fix? We can help if you need help.

**Comment by ktopouzi** [comment]
I tried to create a struct with unnamed fields on Common.h but i don't have any build errors or wrong generated code. @ChrisJMarshall can you please provide the C++ code of yours,  in order to help you further?

**Comment by ddobrev** [comment]
@ChrisJMarshall you haven't provided a test case but we have long since made two major improvements to our naming of nameless fields. First, we switched to numbers instead of multiple underscores. Second, we now directly get the fields of nameless types which types contributed heavily to conflicts. Therefore, this shouldn't happen any more.
