### ISSUE TITLE
Support MS Build Tools toolchain (without VS)

### ISSUE THREAD

**Issue by MichalPolaczyk** [mono/CppSharp#875]
We are trying to run application that uses Cppsharp on our build server where only BuildTools are installed. No VS. When I run the bindings generator.exe that is using cppsharp I get following error:
System.Exception: Could not find a valid Visual Studio toolchain. (pointing towards MSVCToolchain.GetVSToolchain(VisualStudioVersion version)).

Is there any way to run this app without need to install VS?
Thanks.

OS: Windows 7 x64

Target: MSVC/GCC/Clang

**Comment by tritao** [comment]
Which VS version are we talking about?

**Comment by MichalPolaczyk** [comment]
Preferably none :). We cannot install VS on our build machine based on some restrictions we have. We are using only MS BuildTools 2015 Update 3 currently to run our .NET and cpp builds there.

**Comment by tritao** [comment]
My bad, my "VS" I meant which build tools version. So, for versions up to 2015, we look up the include paths in the registry.

If you could help with tracking down the issue, we have helper code that would probably give some insight into what is happening on the machine: https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L62

Just write a very simple C# project that references `CppSharp.dll` and calls `MSVCToolchain. DumpSdks` and paste the result here.

**Comment by MichalPolaczyk** [comment]
The output from DumpSdks():

Visual Studio SDKs:

Windows SDKs:
	(8) C:\Program Files (x86)\Windows Kits\8.0\
	(8) C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\
	(8.1) C:\Program Files (x86)\Windows Kits\8.1\
	(8.1) C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\
	(10) C:\Program Files (x86)\Windows Kits\10\

Windows Kits SDKs:
	(1) C:\Program Files (x86)\Windows Kits\8.1\
	(8) C:\Program Files (x86)\Windows Kits\8.0\
	(10) C:\Program Files (x86)\Windows Kits\10\

.NET Framework SDKs:

MSBuild SDKs:
	(2) C:\Windows\Microsoft.NET\Framework\v2.0.50727\
	(3.5) C:\Windows\Microsoft.NET\Framework\v3.5\
	(4) C:\Windows\Microsoft.NET\Framework\v4.0.30319\
	(14) C:\Program Files (x86)\MSBuild\14.0\bin\

**Comment by tritao** [comment]
As expected there seems to VS SDK found by the registry lookup.

@MichalPolaczyk Can you confirm if you're installing "MS Build Tools 2015" or "Visual C++ Build Tools 2015"? The first only seems to install managed toolchains, while the latter installs C++ build tools.

The only reason we try to look up the VS version is to look up the Windows SDK version that we should be relying on to parse the code.

You can find the code here: https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L165

We already have some fallback code is we cannot find the VS version: https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L185

So what we need to do here is to improve the robustness of the existing code (`GetSystemIncludes`) so that it works even if no VS version is found on the system.

Want to give it a try?

**Comment by MichalPolaczyk** [comment]
Hi,
I attached screen from the machine where you can see installed SDKs and MS and C++ Build tools.
![buildserver_sdk_buildtools](https://user-images.githubusercontent.com/29726906/27674262-3dea08da-5ca5-11e7-9b58-ce5a52ab93e8.PNG)

So what exactly do You have in mind? To make the check not depend only on VS?

**Comment by tritao** [comment]
Yeah, the existing lookup code needs to be reworked a little to not fail early if a VS version is not found on the system.

**Comment by ddobrev** [comment]
@MichalPolaczyk we have long switched to looking system headers up with Clang so both VS and MS Build are skipped now as Clang is significantly more reliable. In other words, while, of course, one still needs the headers themselves, VS is no longer required to be installed.
