### ISSUE TITLE
LLVM usage

### ISSUE THREAD

**Issue by dvirtz** [mono/CppSharp#920]
##### Brief Description
I have two problems with current use of LLVM inside CppSharp.

1. The version is from trunk and not a released version
2. Use of private (not installed) headers such as CodeGen/CodeGenModule.h and others.

These issues prevent getting LLVM from a package manager which in my opinion is a serious downside.
Moreover, the private headers, I believe, can change without notice and break the library.

Do you agree this is problematic and if so do you plan to fix them one day?

**Comment by tritao** [comment]
1. Historically we've never used official LLVM releases because we've always depended on trunk for bug fixes (at some point we even had to apply custom patches).

I believe at this point we could switch to a tagged release, but it does limit us in the future in case we need to depend on a recent commit (like we did recently for VS2017 support).

Since this is related to using LLVM from a package manager, another issue related to this is that Clang does not support shared library exports for its API on Windows, so we need to link statically anyway, which would mean we'd only get the benefit from a shared library on non-Windows platform (Linux presumably?).

2. I think this might could cause issues in the future yes, but it's not been an issue ever since we introduced usage of those APIs. They seem pretty stable at this point in Clang history and unlikely to change. If they do, we'll just update to their equivalents.

I was checking why need them (it's been a while) and it's to get ABI codegen information for return and parameter types. Not using them is not an option since it would mean generating code that crashes at runtime.

Getting the Clang developers to put those APIs under public headers would be an option, but we've been that road before for other APIs and it's a huge waste of our limited time.

We've put a lot of effort and time over the years to make our usage of LLVM as painless as possible to both developers and users, with build scripts for getting, building and packaging pre-compiled LLVM packages for our supported platforms.

If you want to package CppSharp for a package system (which one, by the way?) just do not depend on the package manager's built-in version of LLVM/Clang. All this does really is add a few extra MB of code to the package, and since this is a developer's tool and not a library to be distributed to end-users, I don't think that's an issue to be concerned about.

And it means we can make sure our own version of LLVM is fully-tested and works properly. As we depend on such a heavy set of APIs in Clang, re-using a package manager's version might mean compatibility issues.

**Comment by dvirtz** [comment]
Indeed I thought of adding CppSharp to [Hunter](https://github.com/ruslo/hunter) and I would like to get LLVM from Hunter as well.
The problem with having CppSharp downloading LLVM by itself is described [here](https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html?highlight=dependency#conflict).

**Comment by tritao** [comment]
What I recommend doing is just packaging CppSharp by itself, without any dependency on the package manager's LLVM/Clang library. That should work fine. In the end, all of the LLVM/Clang's code will be statically linked in `CppSharp.CppParser.dll`.

Another issue I forgot to talk about, is that Clang releases (at least on Windows) only provide the C API for linking, while we depend on the C++ API.

**Comment by tritao** [comment]
Closing, let us know if you have any other issues creating the package.
