### ISSUE TITLE
How to enable 64bit struct alignment?

### ISSUE THREAD

**Issue by raizam** [mono/CppSharp#996]
I used to generate the bindings using Sequential Layout, but now I'm realizing this doesn't work for x64.
Then I guess I have to go back to Explicit layout, and it means I'll have to manage 2 versions of the generated binding.

I haven't found the option to generate x64 bindings, how is this configured?
I currently have a CppSharp 32bits setup, do I need to switch to 64bit to generate x64 bindings?

**Comment by tritao** [comment]
Hey,

You need to use the TargetTriple option for this.

https://github.com/mono/CppSharp/blob/master/src/CLI/Generator.cs#L42

In your case it will likely be `x86_64-pc-win32-msvc`.

**Comment by raizam** [comment]
IT FUC**G WORKS
Thanks you so much @tritao 

I'm now generating both versions in a single pass, I've added preprocessors to the generated bindings generating either #if x64 or #if !x64. Maybe this will give you ideas

**Comment by ddobrev** [comment]
@tritao Kimon completed the required functionality. Then I tried switching exclusively to it but we hit that problem with base types and put it off. A few days later it occurred to me this only concerned C++ because there's no inheritance in C. But I had other work to do and then forgot about it.
Basically, it's safe to always use sequential layouts when binding C. I am going to find the issue and reopen it.
